// This file is @generated by Simplex. Do not edit manually.

use std::fmt;
use crate::programs::program::{SimplexProgram, SimplexProgram2};
use simplex::include_simf;
use simplex::program::{ArgumentsTrait, Program};
use simplex::provider::SimplicityNetwork;
use simplex::simplicityhl::elements::secp256k1_zkp::XOnlyPublicKey;

#[derive(Clone)]
pub struct FailureTestProgram {
    program: Program,
}
impl FailureTestProgram {
    pub const SOURCE: &'static str = derived_failure_test::FAILURE_TEST_CONTRACT_SOURCE;
    #[must_use]
    pub fn new(arguments: impl ArgumentsTrait + 'static) -> Self {
        Self {
            program: Program::new(Self::SOURCE, Box::new(arguments)),
        }
    }

    #[must_use]
    fn with_taproot_pubkey(mut self, pub_key: XOnlyPublicKey) -> Self {
        self.program = self.program.with_taproot_pubkey(pub_key);
        self
    }

    #[must_use]
    fn with_storage_capacity(mut self, capacity: usize) -> Self {
        self.program = self.program.with_storage_capacity(capacity);
        self
    }
}

impl AsRef<Program> for FailureTestProgram {
    fn as_ref(&self) -> &Program {
        &self.program
    }
}
impl AsMut<Program> for FailureTestProgram {
    fn as_mut(&mut self) -> &mut Program {
        &mut self.program
    }
}
include_simf!("simf/failure_test.simf");

impl SimplexProgram2 for FailureTestProgram {
    fn get_program(&self) -> &Program {
        &self.program
    }

    fn get_mut_program(&mut self) -> &mut Program {
        &mut self.program
    }
}

impl fmt::Debug for FailureTestProgram {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("FailureTestProgramWrapper").finish()
    }
}