name: Publish simplicityhl-core

on:
  push:
    tags:
      - 'simplicityhl-core-v*'
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  lint:
    name: Lint (reusable)
    uses: ./.github/workflows/lint.yml

  tests:
    name: Tests (reusable)
    uses: ./.github/workflows/tests.yml

  publish:
    name: Publish simplicityhl-core to crates.io
    needs: [lint, tests]
    runs-on: ubuntu-latest
    environment: release
    concurrency:
      group: publish-core-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (stable)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Verify tag matches crate version
        shell: bash
        run: |
          TAG="${GITHUB_REF##*/}"
          VERSION_TAG="${TAG#simplicityhl-core-v}"
          CRATE_VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | select(.name=="simplicityhl-core").version')
          echo "Tag version: $VERSION_TAG"
          echo "Crate version: $CRATE_VERSION"
          if [ "$VERSION_TAG" != "$CRATE_VERSION" ]; then
            echo "Tag version ($VERSION_TAG) does not match crate version ($CRATE_VERSION)"
            exit 1
          fi

      - name: Check package
        run: cargo package -p simplicityhl-core

      - name: Authenticate with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@v1

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish -p simplicityhl-core


